config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments, only: [:create, :destroy]
      resources :likes, only: [:new, :create]
    end
  end

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index, :show] do
        resources :posts, only: [:index, :show, :create], format: :json do
          resources :comments, only: [:create], format: :json
          resources :likes, only: [:create], format: :json
        end
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    can :read, Post, public: true

    return unless current_user.present? # additional permissions for logged in users (they can read their own posts)

    can :read, :all
    can :manage, Post, author: current_user
    can :manage, Comment, author: current_user

    return unless current_user.role == 'admin' # additional permissions for administrators

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: :comments_counter
  belongs_to :author, class_name: 'User'

  validates :text, presence: true, length: { maximum: 120 }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post, counter_cache: :likes_counter
  belongs_to :author, class_name: 'User'

  validates :author_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', counter_cache: :posts_counter
  has_many :comments, dependent: :delete_all, counter_cache: :comments_counter
  has_many :likes, dependent: :delete_all, counter_cache: :likes_counter

  validates :title, presence: true, length: { maximum: 99 }
  validates :text, presence: true, length: { maximum: 600 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_comments
    comments.last(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, foreign_key: 'author_id', counter_cache: :posts_counter, dependent: :destroy
  has_many :comments, inverse_of: 'author', foreign_key: 'author_id', dependent: :delete_all
  has_many :likes, inverse_of: 'author', foreign_key: 'author_id', dependent: :delete_all

  validates :name, presence: true, length: { maximum: 27 }
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.includes(:comments, :likes).last(3)
  end
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < Api::V1::ApplicationController
  def create
    comment = Comment.new(
      text: params[:comment][:text],
      post_id: params[:post_id],
      author_id: current_user.id
    )
    if comment.save
      render json: comment, status: :created
    else
      render json: comment.errors, status: :unprocessable_entity
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController
  def index
    user = User.find(params[:user_id])
    render json: user.posts
  end

  def show
    post = Post.find(params[:id])
    if post.comments_counter.zero?
      render json: post.comments_counter
    else
      render json: post.comments
    end
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::ApplicationController
  def index
    users = User.all
    render json: users
  end

  def show
    user = User.find(params[:id])
    render json: user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :bio, :photo, :role) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :photo, :email, :password, :current_password, :role)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post_id = params[:post_id]

    if @comment.save
      redirect_to user_post_path(params[:user_id], params[:post_id])
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to user_post_path(@user, params[:post_id]), alert: 'Comment Deleted!'
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author_id = current_user.id
    @like.post_id = params[:post_id]

    if @like.save
      redirect_back(:back)
    else
      flash[:alert] = 'Already liked'
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = Post.where(author_id: @user.id).includes(:comments).order(created_at: :desc)
  end

  def show
    @user = User.includes(:posts).find(params[:user_id])
    @post = Post.includes(:comments).find(params[:id])
    @comments = Comment.where(post_id: @post.id).includes(:author).order(created_at: :asc)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(title: params[:post][:title], text: params[:post][:text])
    redirect_to user_post_path(params[:user_id], @post)
  end

  def destroy
    @post = Post.find(params[:id]).destroy

    respond_to do |format|
      format.html { redirect_to user_path(current_user), notice: 'Post Deleted!' }
    end
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.build
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    if @post.save
      redirect_to user_posts_path(current_user.id)
    else
      render :new
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all.order(id: :asc)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.recent_posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer>
  <p>All rights reserved by <a href="https://github.com/raminka13/blog-app" target="blank">RAMINKA</a></p>
</footer>

app/views/layouts/_navbar.html.erb
<nav id="navbar">
  <div id="nav-container">
    <a class="navbar-brand" href="/"><img src=<%= asset_path('blogging.png') %> alt="BlogApp">
    <h2>BlogApp</h2>
    </a>
    <div id="navbar-body">
      <ul class="navbar-list">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link' %>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%=link_to "New post", new_user_post_path(current_user) %>
        </li>
        <li class="nav-item">
          <%= link_to("Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete }) %>
        </li>
        <li class="nav-item">
          <%= link_to edit_user_registration_path, class: 'nav-link' do %>
          <p class="logged-user">Log as <%= current_user.role %><br><strong><%= current_user.name %></strong></p>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: 'nav-link' %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= render partial: 'layouts/navbar' %>
    <main>
      <h3 class="notice"><%= notice %></h3>
      <h3 class="alert"><%= alert %></h3>
      <%= yield %>
    </main>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/new.html.erb
<h1>Likes#new</h1>
<p>Find me in app/views/likes/new.html.erb</p>

app/views/posts/_form.html.erb
  <div class="new-comment">
    <%= form_with model: Comment, url: user_post_comments_path(@user, @post), class: "comment-form" do |f| %>
      <div>
        <%= f.text_field :text, placeholder: "New Comment" %>
      </div>

        <%= f.submit 'Add Comment' %>
    <% end %>
  </div>

app/views/posts/_post.html.erb
<div class="post-card">
  <%= link_to user_post_path(post.author_id, post.id), class: 'post-title' do %>
    <h4><strong><%= post.title %></strong> by: <%= post.author.name %></h4>
  <%end%>
  <p class="post-text">
    <% if post.id.to_s == params[:id] %>
      <%= post.text %>
    <% else %>
      <%= post.text.truncate(150) %> <strong><%= link_to 'see more', user_post_path(post.author_id, post.id) %></strong>
    <% end %>
  </p>
  <div class="destroy-edit">
    <% if can? :destroy, post %>
      <%= form_with model: post, class: 'destroy-form', url: user_post_path(post.author_id, post.id), method: :delete do |form| %>
        <div>
          <%= form.submit "Delete Post", class: 'post-destroy' %><br>
        </div>
      <% end %>
    <% end %>
    <% if can? :update, post %>
      <%= link_to "Edit Post", edit_user_post_path(post.author_id, post.id), class: 'post-edit'  %>
    <% end %>
    <%= form_with model: @like, url: user_post_likes_path(post.author_id, post.id), class: "new-like" do |form| %>
      <div>
        <%= form.submit "Like Post", class: 'new-like-btn' %><br>
      </div>
    <% end %>
  </div>
  <div class="social-post">
    <span>📝 Comments: <%= post.comments_counter %></span>
    <span>❤️ Likes: <%=post.likes_counter%></span>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <h2 class="new-post-title">Edit Post</h2>
  <% if can? :manage, @post %>
    <%= form_with model: @post, url: user_post_path, class: 'post-form' do |f| %>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :text %>
        <%= f.text_area :text %>
      </div>
        <%= f.submit %>
    <% end %>
  <% else %>
    What are you doing here? Go back!!
  <% end %>
  <%= link_to "Back", :back, class: 'back-btn' %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <%= render @user %>
  <%@posts.each do |post|%>
    <%= render post %>
    <div class='post-comments'>
      <% if post.comments_counter == 0 %>
        <p><strong>No comments yet</strong></p>
      <% else %>
        <% post.recent_comments.each do |comm| %>
         <p><strong><%= comm.author.name %>: </strong><%=comm.text%></p>
        <%end%>
      <%end%>
    </div>
  <%end%>


  <%= link_to user_path(@user), class: 'all-post-btn' do %>
    Back to <strong><%= @user.name %></strong> profile
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h2 class="new-post-title">Create a New Post</h2>
  <% if can? :manage, @user.posts.first %>
    <%= form_with model: @post, url: user_posts_path, class: 'post-form' do |f| %>
      <div>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
      <div>
        <%= f.label :text %>
        <%= f.text_area :text %>
      </div>
        <%= f.submit %>
    <% end %>
  <% else %>
    What are you doing here? Go back!!
  <% end %>
  <%= link_to "Back", :back, class: 'back-btn' %>
</div>

app/views/posts/show.html.erb
<div class="container">

  <%= render @user %>
  <%= render @post %>

  <div class= "post-comments">
    <% if @post.comments_counter == 0 %>
      <p><strong>No comments yet</strong></p>
    <% else %>
      <% @comments.includes(:author).each do |comm|%>
        <div class='comment'>
          <p><strong><%= comm.author.name %>: </strong><%= comm.text %></p>
          <% if can? :destroy, comm %>
            <%= form_with model: Comment, class: 'destroy-form', url: user_post_comment_path(comm.author_id, comm.post_id, comm.id), method: :delete do |form| %>
              <%= form.submit "❌", class: 'comment-destroy' %><br>
            <% end %>
          <% end %>
        </div>
      <%end%>
    <% end %>
  </div>

  <%= render "form" %>

  <%= link_to "Back to posts", user_posts_path, class: 'all-post-btn' %>
</div>

app/views/users/_user.html.erb
<li class="user-card">
  <%= link_to user_path(user) do %>
    <div class="user-card-img">
      <% if user.photo.empty? %>
        <%= image_tag "img_placeholder.jpg" %>
      <% else %>
        <img src=<%= user.photo %>>
      <% end %>
    </div>
    <div class="card-body">
      <h2 class="card-title"><%= user.name %></h2>
      <p><%= user.bio.truncate(120) %><strong>see more...</strong></p>
    </div>
  <% end %>

  <div class="posts-counter">
    <% if user.posts_counter == 0 %>
      <span>No Posts Yet</span>
    <% else %>
      <span><strong><%= user.posts_counter %></strong></span>
      <span>posts</span>
    <% end %>
  </div>
</li>

app/views/users/index.html.erb
<div class="container">
  <ul class="users-list">
    <%= render partial: 'user', collection: @users %>
  </ul>
</div>

app/views/users/show.html.erb
<div class="container">
  <%= render partial: @user %>
  <div class="user-bio">
    <h5>Bio:</h5>
    <p><%= @user.bio %></p>
  </div>
  <%= render @posts %>
  <%= link_to ("See all posts"),user_posts_path(@user.id), class: 'all-post-btn' %>
</div>